/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistemas;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

public class DistribucionP extends javax.swing.JFrame {
    //Declaramos una variable que cada vez que se ejecute el programa se inicializara con el valor 0
    double sumaT=0;
 
    public DistribucionP() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtErrorMedia1 = new javax.swing.JTextField();
        lblLambda = new javax.swing.JLabel();
        lblOcurrencia = new javax.swing.JLabel();
        txtErrorMedia2 = new javax.swing.JTextField();
        txtDiferenciaEntreMedias = new javax.swing.JTextField();
        por = new javax.swing.JLabel();
        por1 = new javax.swing.JLabel();
        jLambda = new javax.swing.JLabel();
        lblLambda3 = new javax.swing.JLabel();
        cmdEncontrarErrorEstandar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cmdBorrar = new javax.swing.JButton();
        txtVar1 = new javax.swing.JTextField();
        lblLambda2 = new javax.swing.JLabel();
        txtVar2 = new javax.swing.JTextField();
        cmdEncontrarSx = new javax.swing.JButton();
        lblLambda1 = new javax.swing.JLabel();
        lblLambda4 = new javax.swing.JLabel();
        lblLambda5 = new javax.swing.JLabel();
        txtN1 = new javax.swing.JTextField();
        txtN2 = new javax.swing.JTextField();
        cmdEncontrarZc = new javax.swing.JButton();
        txtSx = new javax.swing.JTextField();
        lblLambda6 = new javax.swing.JLabel();
        lblLambda7 = new javax.swing.JLabel();
        txtMedia1 = new javax.swing.JTextField();
        txtMedia2 = new javax.swing.JTextField();
        txtZc = new javax.swing.JTextField();
        cmdEncontrarDevSx = new javax.swing.JButton();
        lblLambda16 = new javax.swing.JLabel();
        lblLambda17 = new javax.swing.JLabel();
        txtDesv1 = new javax.swing.JTextField();
        txtDesv2 = new javax.swing.JTextField();
        lblZTabla = new javax.swing.JLabel();
        txtZt = new javax.swing.JTextField();
        cmdSig5 = new javax.swing.JButton();
        cmdSig10 = new javax.swing.JButton();
        cmdSig15 = new javax.swing.JButton();
        lblNocolas = new javax.swing.JLabel();
        txtNocolas = new javax.swing.JTextField();
        cmdSig2 = new javax.swing.JButton();
        cmdSig1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblTitulo3 = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        cmdBorrart = new javax.swing.JButton();
        txtVar1t = new javax.swing.JTextField();
        lblLambda8 = new javax.swing.JLabel();
        txtVar2t = new javax.swing.JTextField();
        lblLambda9 = new javax.swing.JLabel();
        lblLambda10 = new javax.swing.JLabel();
        lblLambda11 = new javax.swing.JLabel();
        txtN1t = new javax.swing.JTextField();
        txtN2t = new javax.swing.JTextField();
        cmdEncontrarZct = new javax.swing.JButton();
        lblLambda12 = new javax.swing.JLabel();
        lblLambda13 = new javax.swing.JLabel();
        txtMedia1t = new javax.swing.JTextField();
        txtMedia2t = new javax.swing.JTextField();
        txtTc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTt = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        txtErrorMedia1t = new javax.swing.JTextField();
        lblLambda14 = new javax.swing.JLabel();
        lblOcurrencia1 = new javax.swing.JLabel();
        txtErrorMedia2t = new javax.swing.JTextField();
        txtDiferenciaEntreMediast = new javax.swing.JTextField();
        por2 = new javax.swing.JLabel();
        por3 = new javax.swing.JLabel();
        jLambda1 = new javax.swing.JLabel();
        lblLambda15 = new javax.swing.JLabel();
        cmdEncontrarErrorEstandart = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        cmdComprobar = new javax.swing.JButton();
        lblHipotesis = new javax.swing.JLabel();
        lblTitulo4 = new javax.swing.JLabel();
        cmdComprobart = new javax.swing.JButton();
        lblHipotesist = new javax.swing.JLabel();
        lblLambda18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        txtErrorMedia1.setEditable(false);

        lblLambda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLambda.setText("Error Estandar de la Media 1:");

        lblOcurrencia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOcurrencia.setText("Error Estandar de la Media 2:");

        txtErrorMedia2.setEditable(false);

        txtDiferenciaEntreMedias.setEditable(false);
        txtDiferenciaEntreMedias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiferenciaEntreMediasActionPerformed(evt);
            }
        });

        por.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        por1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLambda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblLambda3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLambda3.setText("Diferencia:");

        cmdEncontrarErrorEstandar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cmdEncontrarErrorEstandar.setText("Encontrar Error Estandar");
        cmdEncontrarErrorEstandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEncontrarErrorEstandarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(por1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLambda)
                            .addComponent(lblOcurrencia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtErrorMedia2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(txtErrorMedia1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblLambda3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDiferenciaEntreMedias))
                            .addComponent(cmdEncontrarErrorEstandar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLambda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(por, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLambda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLambda)
                                    .addComponent(txtErrorMedia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOcurrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtErrorMedia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLambda3)
                            .addComponent(txtDiferenciaEntreMedias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdEncontrarErrorEstandar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(por, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(por1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        cmdBorrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdBorrar.setText("Limpiar Datos");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });

        lblLambda2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLambda2.setText("Varianza 1:");

        cmdEncontrarSx.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cmdEncontrarSx.setText("Encontrar Sx1-Sx2 con S^2:");
        cmdEncontrarSx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEncontrarSxActionPerformed(evt);
            }
        });

        lblLambda1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLambda1.setText("Varianza 2:");

        lblLambda4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLambda4.setText("N1:");

        lblLambda5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLambda5.setText("N2:");

        txtN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN1ActionPerformed(evt);
            }
        });

        txtN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN2ActionPerformed(evt);
            }
        });

        cmdEncontrarZc.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cmdEncontrarZc.setText("Encontrar Zc");
        cmdEncontrarZc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEncontrarZcActionPerformed(evt);
            }
        });

        txtSx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSxActionPerformed(evt);
            }
        });

        lblLambda6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLambda6.setText("Media 1:");

        lblLambda7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLambda7.setText("Media 2:");

        cmdEncontrarDevSx.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cmdEncontrarDevSx.setText("Encontrar Sx1-Sx2 con S:");
        cmdEncontrarDevSx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEncontrarDevSxActionPerformed(evt);
            }
        });

        lblLambda16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLambda16.setText("Desv. Estan 1:");

        lblLambda17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLambda17.setText("Desv. Estan 2:");

        lblZTabla.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblZTabla.setText("Z Tabla:");

        cmdSig5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmdSig5.setText("Significancia 5%");
        cmdSig5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSig5ActionPerformed(evt);
            }
        });

        cmdSig10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmdSig10.setText("Significancia 10%");
        cmdSig10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSig10ActionPerformed(evt);
            }
        });

        cmdSig15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmdSig15.setText("Significancia 15%");
        cmdSig15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSig15ActionPerformed(evt);
            }
        });

        lblNocolas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNocolas.setText("No. de colas:");

        cmdSig2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmdSig2.setText("Significancia 2%");
        cmdSig2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSig2ActionPerformed(evt);
            }
        });

        cmdSig1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmdSig1.setText("Significancia 1%");
        cmdSig1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSig1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(lblLambda2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtVar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(lblLambda1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtVar2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(lblLambda6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtMedia1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cmdEncontrarSx)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblLambda7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMedia2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lblLambda5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtN2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lblLambda4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtN1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblLambda17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtDesv2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(lblLambda16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtDesv1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSx)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdEncontrarDevSx))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(lblZTabla)
                                    .addGap(30, 30, 30))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(lblNocolas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(14, 14, 14)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtZt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNocolas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(cmdEncontrarZc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtZc, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(131, 131, 131))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdSig1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdSig2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdBorrar)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cmdSig5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdSig10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdSig15)))
                .addGap(6, 6, 6))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLambda2)
                    .addComponent(txtVar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLambda4)
                    .addComponent(txtN1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLambda16)
                    .addComponent(txtDesv1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLambda1)
                    .addComponent(txtVar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLambda5)
                    .addComponent(txtN2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLambda17)
                    .addComponent(txtDesv2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdEncontrarSx, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSx)
                    .addComponent(cmdEncontrarDevSx, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLambda6)
                    .addComponent(lblLambda7)
                    .addComponent(txtMedia1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedia2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdEncontrarZc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtZc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNocolas)
                    .addComponent(txtNocolas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZTabla)
                    .addComponent(txtZt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSig10)
                    .addComponent(cmdSig15)
                    .addComponent(cmdSig5)
                    .addComponent(cmdSig1)
                    .addComponent(cmdSig2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setToolTipText("");

        lblTitulo3.setBackground(new java.awt.Color(255, 255, 0));
        lblTitulo3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo3.setText("Prueba de Hipotesis para 2 grupos indepentientes (Parametrica)");
        lblTitulo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo3)
                .addGap(38, 38, 38))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblTitulo1.setBackground(new java.awt.Color(255, 255, 0));
        lblTitulo1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblTitulo1.setText("Jose Andres Maldonado García");
        lblTitulo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTitulo2.setBackground(new java.awt.Color(255, 255, 0));
        lblTitulo2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblTitulo2.setText("Kenneth Rodrigo Herrera Gómez");
        lblTitulo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel6.setBackground(new java.awt.Color(255, 204, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        cmdBorrart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdBorrart.setText("Limpiar Datos ");
        cmdBorrart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrartActionPerformed(evt);
            }
        });

        lblLambda8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLambda8.setText("Desv Est 1:");

        lblLambda9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLambda9.setText("Desv Est 2:");

        lblLambda10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLambda10.setText("N1:");

        lblLambda11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLambda11.setText("N2:");

        cmdEncontrarZct.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cmdEncontrarZct.setText("Encontrar Tc");
        cmdEncontrarZct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEncontrarZctActionPerformed(evt);
            }
        });

        lblLambda12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLambda12.setText("Media 1:");

        lblLambda13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLambda13.setText("Media 2:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("T Tabla:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(lblLambda8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtVar1t, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(lblLambda9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtVar2t, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblLambda12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMedia1t, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblLambda11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtN2t, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblLambda10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtN1t, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblLambda13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMedia2t, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdBorrart)
                .addGap(74, 74, 74))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdEncontrarZct)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTc)
                    .addComponent(txtTt))
                .addGap(77, 77, 77))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLambda8)
                    .addComponent(txtVar1t, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLambda10)
                    .addComponent(txtN1t, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLambda9)
                    .addComponent(txtVar2t, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLambda11)
                    .addComponent(txtN2t, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLambda12)
                    .addComponent(lblLambda13)
                    .addComponent(txtMedia1t, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedia2t, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdEncontrarZct, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdBorrart, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 204, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        txtErrorMedia1t.setEditable(false);

        lblLambda14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLambda14.setText("Error Estandar de la Media 1:");

        lblOcurrencia1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOcurrencia1.setText("Error Estandar de la Media 2:");

        txtErrorMedia2t.setEditable(false);

        txtDiferenciaEntreMediast.setEditable(false);

        por2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        por3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLambda1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblLambda15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLambda15.setText("Diferencia:");

        cmdEncontrarErrorEstandart.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cmdEncontrarErrorEstandart.setText("Encontrar Error Estandar");
        cmdEncontrarErrorEstandart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEncontrarErrorEstandartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(por3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLambda14)
                            .addComponent(lblOcurrencia1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtErrorMedia2t, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(txtErrorMedia1t))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(lblLambda15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDiferenciaEntreMediast))
                            .addComponent(cmdEncontrarErrorEstandart))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLambda1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(por2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLambda1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLambda14)
                                    .addComponent(txtErrorMedia1t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOcurrencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtErrorMedia2t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLambda15)
                            .addComponent(txtDiferenciaEntreMediast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdEncontrarErrorEstandart, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(por2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(por3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setText("Encontrar T");
        lblTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cmdComprobar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdComprobar.setText("Comprobar Hipotesis ");
        cmdComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdComprobarActionPerformed(evt);
            }
        });

        lblHipotesis.setBackground(new java.awt.Color(255, 255, 255));
        lblHipotesis.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblTitulo4.setBackground(new java.awt.Color(255, 255, 0));
        lblTitulo4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo4.setText("Encontrar Z");
        lblTitulo4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cmdComprobart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdComprobart.setText("Comprobar Hipotesis");
        cmdComprobart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdComprobartActionPerformed(evt);
            }
        });

        lblHipotesist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblLambda18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLambda18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistemas/TT.jpg"))); // NOI18N
        lblLambda18.setText(":T");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTitulo2)
                            .addComponent(lblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(236, 236, 236)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addComponent(lblTitulo4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmdComprobar)
                                .addGap(27, 27, 27)
                                .addComponent(lblHipotesis, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblTitulo)
                                    .addGap(199, 199, 199))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(lblLambda18)
                                    .addGap(37, 37, 37))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cmdComprobart)
                                    .addGap(54, 54, 54)
                                    .addComponent(lblHipotesist, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap()))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(258, 258, 258))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lblLambda18))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitulo2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmdComprobar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHipotesis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdComprobart, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(lblHipotesist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        // TODO add your handling code here:
        txtVar1.setText("");
          txtVar2.setText("");
          txtN1.setText("");
          txtN2.setText("");
          txtDesv1.setText("");
          txtDesv2.setText("");
          txtSx.setText("");
          txtMedia1.setText("");
          txtMedia2.setText("");
          txtZc.setText("");
          txtZt.setText("");
          txtNocolas.setText("");
          txtErrorMedia1.setText("");
          txtErrorMedia2.setText("");
          txtDiferenciaEntreMedias.setText("");
          lblHipotesis.setText("");
          
          //activacion de bontones
          
          txtVar1.setEnabled(true);
          txtVar2.setEnabled(true);
          txtDesv1.setEnabled(true);
          txtDesv2.setEnabled(true);
          txtN1.setEnabled(true);
          txtN2.setEnabled(true);
          
          
        
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdEncontrarSxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEncontrarSxActionPerformed
        // TODO add your handling code here:
        float encontrarSx;
        //Formula para encontrar el valor de lambda (si en dado caso no lo tenemos)
        encontrarSx= (float) (Math.sqrt(Float.parseFloat(txtVar1.getText())/Float.parseFloat(txtN1.getText())+(Float.parseFloat(txtVar2.getText())/Float.parseFloat(txtN2.getText()))));
        DecimalFormat df=new DecimalFormat("#.0000");
        txtSx.setText(String.valueOf(df.format(encontrarSx)));
        txtVar1.setEnabled(false);
        txtVar2.setEnabled(false);
        txtDesv1.setEnabled(false);
        txtDesv2.setEnabled(false);
        txtN1.setEnabled(false);
        txtN2.setEnabled(false);
        
    }//GEN-LAST:event_cmdEncontrarSxActionPerformed

    private void cmdEncontrarZcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEncontrarZcActionPerformed
        // TODO add your handling code here:
        float encontrarZc;
        encontrarZc=(Float.parseFloat(txtMedia1.getText())-Float.parseFloat(txtMedia2.getText()))/Float.parseFloat(txtSx.getText());
        DecimalFormat df=new DecimalFormat("#.0000");
        txtZc.setText(String.valueOf(df.format(encontrarZc)));
        
    }//GEN-LAST:event_cmdEncontrarZcActionPerformed

    private void cmdEncontrarErrorEstandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEncontrarErrorEstandarActionPerformed
        // TODO add your handling code here:
        float encontrarError1, encontrarError2, Diferencia;
        if(true==txtVar1.isEnabled()){
        encontrarError1=(float) (Math.sqrt(Float.parseFloat(txtVar1.getText()))/Math.sqrt(Float.parseFloat(txtN1.getText())));
        encontrarError2=(float) (Math.sqrt(Float.parseFloat(txtVar2.getText()))/Math.sqrt(Float.parseFloat(txtN2.getText())));            
        }else{
        encontrarError1=(float) (Float.parseFloat(txtDesv1.getText())/Math.sqrt(Float.parseFloat(txtN1.getText())));
        encontrarError2=(float) (Float.parseFloat(txtDesv2.getText())/Math.sqrt(Float.parseFloat(txtN2.getText())));            
            
        }
        Diferencia=encontrarError1-encontrarError2;
        if(encontrarError1<encontrarError2){
            Diferencia=Diferencia*(-1);
        }
        DecimalFormat df=new DecimalFormat("#.0000");
        txtErrorMedia1.setText(String.valueOf(df.format(encontrarError1)));
        txtErrorMedia2.setText(String.valueOf(df.format(encontrarError2)));
        txtDiferenciaEntreMedias.setText(String.valueOf(df.format(Diferencia)));
        
        
        
    }//GEN-LAST:event_cmdEncontrarErrorEstandarActionPerformed

    private void txtSxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSxActionPerformed

    private void cmdBorrartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrartActionPerformed
       
        txtVar1t.setText("");
        txtVar2t.setText("");
        txtN1t.setText("");
        txtN2t.setText("");
        txtMedia1t.setText("");
        txtMedia2t.setText("");
        txtTc.setText("");
        txtErrorMedia1t.setText("");
        txtErrorMedia2t.setText("");
        txtDiferenciaEntreMediast.setText("");
        txtTt.setText("");
        
        
        
    }//GEN-LAST:event_cmdBorrartActionPerformed

    private void cmdEncontrarZctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEncontrarZctActionPerformed
        // TODO add your handling code here:
        float encontrarDenominador, encontrarNumerador;
        encontrarNumerador=Float.parseFloat(txtMedia1t.getText())-Float.parseFloat(txtMedia2t.getText());
        encontrarDenominador=(float) Math.sqrt((((Float.parseFloat(txtN1t.getText())-1)*(Float.parseFloat(txtVar1t.getText())*Float.parseFloat(txtVar1t.getText())))+((Float.parseFloat(txtN2t.getText())-1)*(Float.parseFloat(txtVar2t.getText())*Float.parseFloat(txtVar2t.getText()))))/(Float.parseFloat(txtN1t.getText())+Float.parseFloat(txtN2t.getText())-2));
        System.out.println(encontrarDenominador);
        encontrarDenominador=(float) (encontrarDenominador * Math.sqrt((1/Float.parseFloat(txtN1t.getText()))+(1/Float.parseFloat(txtN2t.getText()))));
        System.out.println(encontrarDenominador);
        DecimalFormat df=new DecimalFormat("#.0000");
        txtTc.setText(String.valueOf(df.format(encontrarNumerador/encontrarDenominador)));
        System.out.print(encontrarNumerador);
        
        
    }//GEN-LAST:event_cmdEncontrarZctActionPerformed

    private void cmdEncontrarErrorEstandartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEncontrarErrorEstandartActionPerformed
        // TODO add your handling code here:
        float encontrarError1, encontrarError2, Diferencia;
        encontrarError1=(float) (Math.sqrt(Float.parseFloat(txtVar1t.getText()))/Math.sqrt(Float.parseFloat(txtN1t.getText())));
        encontrarError2=(float) (Math.sqrt(Float.parseFloat(txtVar2t.getText()))/Math.sqrt(Float.parseFloat(txtN2t.getText())));
        Diferencia=encontrarError1-encontrarError2;
        if(encontrarError1<encontrarError2){
            Diferencia=Diferencia*(-1);
        }
        DecimalFormat df=new DecimalFormat("#.0000");
        txtErrorMedia1t.setText(String.valueOf(df.format(encontrarError1)));
        txtErrorMedia2t.setText(String.valueOf(df.format(encontrarError2)));
        txtDiferenciaEntreMediast.setText(String.valueOf(df.format(Diferencia)));        
    }//GEN-LAST:event_cmdEncontrarErrorEstandartActionPerformed

    private void cmdEncontrarDevSxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEncontrarDevSxActionPerformed
        // TODO add your handling code here:
        float encontrarSx;
        //Formula para encontrar el valor de lambda (si en dado caso no lo tenemos)
        encontrarSx= (float) (Math.sqrt((Float.parseFloat(txtDesv1.getText())*Float.parseFloat(txtDesv1.getText()))/Float.parseFloat(txtN1.getText())+((Float.parseFloat(txtDesv2.getText())*Float.parseFloat(txtDesv2.getText()))/Float.parseFloat(txtN2.getText()))));
        DecimalFormat df=new DecimalFormat("#.0000");
        txtSx.setText(String.valueOf(df.format(encontrarSx)));        
        txtVar1.setEnabled(false);
        txtVar2.setEnabled(false);
        txtDesv1.setEnabled(false);
        txtDesv2.setEnabled(false);
        txtN1.setEnabled(false);
        txtN2.setEnabled(false);
          
    }//GEN-LAST:event_cmdEncontrarDevSxActionPerformed

    private void txtN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN1ActionPerformed
        if(Float.parseFloat(txtN1.getText())<=30){
         txtN2.setText("");
         JOptionPane.showMessageDialog(this,"Error detectado: Para el estadistico Z es necesaria una muestra mayor a 30 datos");
        }
    }//GEN-LAST:event_txtN1ActionPerformed

    private void txtN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN2ActionPerformed
        if(Float.parseFloat(txtN2.getText())<=30){
 
            JOptionPane.showMessageDialog(this,"Error detectado: Para el estadistico Z es necesaria una muestra mayor a 30 datos");
        }
    }//GEN-LAST:event_txtN2ActionPerformed

    private void cmdSig5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSig5ActionPerformed
        
        if(Integer.parseInt(txtNocolas.getText())==1)
            {
                   txtZt.setText("1.65");
            }
        
        else if (Integer.parseInt(txtNocolas.getText())==2)
            {
                   txtZt.setText("1.96");
            }
    }//GEN-LAST:event_cmdSig5ActionPerformed

    private void cmdSig10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSig10ActionPerformed
        if(Integer.parseInt(txtNocolas.getText())==1)
            {
                   txtZt.setText("1.28");
            }
        
        else if (Integer.parseInt(txtNocolas.getText())==2)
            {
                   txtZt.setText("1.65");
            }
    }//GEN-LAST:event_cmdSig10ActionPerformed

    private void cmdSig15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSig15ActionPerformed
        if(Integer.parseInt(txtNocolas.getText())==1)
            {
                   txtZt.setText("1.04");
            }
        
        else if (Integer.parseInt(txtNocolas.getText())==2)
            {
                   txtZt.setText("1.44");
            }
    }//GEN-LAST:event_cmdSig15ActionPerformed

    private void cmdComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdComprobarActionPerformed
        if(Float.parseFloat(txtZc.getText())>(-1*(Float.parseFloat(txtZt.getText())))&&Float.parseFloat(txtZc.getText())<Float.parseFloat(txtZt.getText()))
        {
            lblHipotesis.setText("Se Acepta la hipotesis nula");
        }
        
        else 
        {
            lblHipotesis.setText("Se Rechaza la hipotesis nula");
        }
    }//GEN-LAST:event_cmdComprobarActionPerformed

    private void txtDiferenciaEntreMediasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiferenciaEntreMediasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiferenciaEntreMediasActionPerformed

    private void cmdSig2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSig2ActionPerformed
        if(Integer.parseInt(txtNocolas.getText())==1)
            {
                   txtZt.setText("2.05");
            }
        
        else if (Integer.parseInt(txtNocolas.getText())==2)
            {
                   txtZt.setText("2.33");
            }
    }//GEN-LAST:event_cmdSig2ActionPerformed

    private void cmdSig1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSig1ActionPerformed
        if(Integer.parseInt(txtNocolas.getText())==1)
            {
                   txtZt.setText("2.13");
            }
        
        else if (Integer.parseInt(txtNocolas.getText())==2)
            {
                   txtZt.setText("2.58");
            }
    }//GEN-LAST:event_cmdSig1ActionPerformed

    private void cmdComprobartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdComprobartActionPerformed
         if(Float.parseFloat(txtTc.getText())>(-1*(Float.parseFloat(txtTt.getText())))&&Float.parseFloat(txtTc.getText())<Float.parseFloat(txtTt.getText()))
        {
            lblHipotesist.setText("Se Acepta la hipotesis nula");
        }
         else 
         {
              lblHipotesist.setText("Se Rechaza la hipotesis nula");
         }
    }//GEN-LAST:event_cmdComprobartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DistribucionP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DistribucionP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DistribucionP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DistribucionP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DistribucionP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdBorrart;
    private javax.swing.JButton cmdComprobar;
    private javax.swing.JButton cmdComprobart;
    private javax.swing.JButton cmdEncontrarDevSx;
    private javax.swing.JButton cmdEncontrarErrorEstandar;
    private javax.swing.JButton cmdEncontrarErrorEstandart;
    private javax.swing.JButton cmdEncontrarSx;
    private javax.swing.JButton cmdEncontrarZc;
    private javax.swing.JButton cmdEncontrarZct;
    private javax.swing.JButton cmdSig1;
    private javax.swing.JButton cmdSig10;
    private javax.swing.JButton cmdSig15;
    private javax.swing.JButton cmdSig2;
    private javax.swing.JButton cmdSig5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLambda;
    private javax.swing.JLabel jLambda1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblHipotesis;
    private javax.swing.JLabel lblHipotesist;
    private javax.swing.JLabel lblLambda;
    private javax.swing.JLabel lblLambda1;
    private javax.swing.JLabel lblLambda10;
    private javax.swing.JLabel lblLambda11;
    private javax.swing.JLabel lblLambda12;
    private javax.swing.JLabel lblLambda13;
    private javax.swing.JLabel lblLambda14;
    private javax.swing.JLabel lblLambda15;
    private javax.swing.JLabel lblLambda16;
    private javax.swing.JLabel lblLambda17;
    private javax.swing.JLabel lblLambda18;
    private javax.swing.JLabel lblLambda2;
    private javax.swing.JLabel lblLambda3;
    private javax.swing.JLabel lblLambda4;
    private javax.swing.JLabel lblLambda5;
    private javax.swing.JLabel lblLambda6;
    private javax.swing.JLabel lblLambda7;
    private javax.swing.JLabel lblLambda8;
    private javax.swing.JLabel lblLambda9;
    private javax.swing.JLabel lblNocolas;
    private javax.swing.JLabel lblOcurrencia;
    private javax.swing.JLabel lblOcurrencia1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTitulo4;
    private javax.swing.JLabel lblZTabla;
    private javax.swing.JLabel por;
    private javax.swing.JLabel por1;
    private javax.swing.JLabel por2;
    private javax.swing.JLabel por3;
    private javax.swing.JTextField txtDesv1;
    private javax.swing.JTextField txtDesv2;
    private javax.swing.JTextField txtDiferenciaEntreMedias;
    private javax.swing.JTextField txtDiferenciaEntreMediast;
    private javax.swing.JTextField txtErrorMedia1;
    private javax.swing.JTextField txtErrorMedia1t;
    private javax.swing.JTextField txtErrorMedia2;
    private javax.swing.JTextField txtErrorMedia2t;
    private javax.swing.JTextField txtMedia1;
    private javax.swing.JTextField txtMedia1t;
    private javax.swing.JTextField txtMedia2;
    private javax.swing.JTextField txtMedia2t;
    private javax.swing.JTextField txtN1;
    private javax.swing.JTextField txtN1t;
    private javax.swing.JTextField txtN2;
    private javax.swing.JTextField txtN2t;
    private javax.swing.JTextField txtNocolas;
    private javax.swing.JTextField txtSx;
    private javax.swing.JTextField txtTc;
    private javax.swing.JTextField txtTt;
    private javax.swing.JTextField txtVar1;
    private javax.swing.JTextField txtVar1t;
    private javax.swing.JTextField txtVar2;
    private javax.swing.JTextField txtVar2t;
    private javax.swing.JTextField txtZc;
    private javax.swing.JTextField txtZt;
    // End of variables declaration//GEN-END:variables
}
